modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/petrolpark/Destroy/issues"
license="MIT License"

[[mods]]
modId="destroy"
version="${file.jarVersion}"
displayName="Destroy"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-destroy"
logoFile="logo.png"
#credits=""
authors="petrolpark"
description='''A destructive chemistry-based add-on to Create.'''

[[dependencies.destroy]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.destroy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.destroy]]
	modId="create"
	mandatory=true
	versionRange="[mc1.18.2_v0.5.0,)"
	ordering="NONE"
	side="BOTH"
	
[[dependencies.destroy]]
	modId="flywheel"
	mandatory=true
	versionRange="[1.18-0.6.3,)"
	ordering="NONE"
	side="BOTH"